### ISSUE TITLE
是否意味着用这个包vue都能跑在ie8上？

### ISSUE THREAD

**Issue by luanwulin** [ambit-tsai/object-defineproperty-ie#5]
rt，不计较性能问题的话，上一个vue依赖的还是defintproperty

**Comment by ambit-tsai** [comment]
并不能，这个库只模拟了 `defineProperty` 的部分行为，而 Vue 2.x 用到了未模拟的部分，所以……

**Comment by luanwulin** [comment]
@ambit-tsai 是不是只用到setter和getter部分都能用这个包来模拟？比如说webpack经常打包出来的会带上些defineProperty的getter

**Comment by ambit-tsai** [comment]
它支持 configurable、value、writable、get、set 这5个描述符，所以getter与setter功能是支持的，甚至IE5下也测试通过了。
主要问题在于原生 `defineProperty` 直接作用于目标对象上：
```
var obj = {};
Object.defineProperty(obj, 'prop', {value: 123});
// obj => {prop: 123}
// 直接在 obj 上定义 prop 属性
```
此库提供的 `defineProperty` 会生成一个新对象：
```
var oldObj = {};
var newObj = Object.defineProperty(oldObj, 'prop', {value: 123});
// oldObj => {}
// newObj => {prop: 123}
```
使用的时候要注意这一点

**Comment by luanwulin** [comment]
如果是这样的话没法用呢，很多```Object.defineProperty```过后就是直接用原始obj的。是否有办法把```newObj```的东西拷贝到```oldObj```上面去？

**Comment by ambit-tsai** [comment]
可以拷贝属性值，无法拷贝getter与setter

**Comment by ambit-tsai** [comment]
想在IE8下用 `defineProperty`，只要把代码稍微改造下就行了
```
var obj = {};
obj = Object.defineProperty(obj, 'prop', {value: 123});
```

**Comment by luanwulin** [comment]
这样不行呢兄弟，如果```obj``` 是一个像你写的那样新对象还好，如果是一个已经有属性的，```Object.defineProperty```过后返回的新对象赋值后，会造成以前属性都被覆盖了吧？

**Comment by ambit-tsai** [comment]
原有属性会拷贝至新对象上，可以参考 README.md 的 Usage 示例
